import React from "react";
import type { Metadata } from "next";
import { Container } from "@/components/ui/Container";
import { AuditForm } from "@/components/forms/AuditForm";
import {
  Sparkles,
  Gauge,
  MapPin,
  Smartphone,
  MessageSquare,
  ShieldCheck,
  CheckCircle2,
  Clock,
} from "lucide-react";

export const metadata: Metadata = {
  title: "Free Digital Presence Audit — SETU Client Acquisition System",
  description:
    "Request a free 100% actionable digital presence audit. We inspect your Google Maps ranking, mobile speed, conversion bottlenecks, and WhatsApp lead flow.",
};

export default function AuditPage({
  searchParams,
}: {
  searchParams?: { [key: string]: string | string[] | undefined };
}) {
  const selectedPackage = typeof searchParams?.package === "string" ? searchParams.package : undefined;

  const auditFeatures = [
    {
      icon: <Gauge className="w-5 h-5 text-blue-600" />,
      title: "Core Web Vitals & Speed",
      description: "We test your site on real 4G/5G mobile networks and calculate bounce-rate risk.",
    },
    {
      icon: <MapPin className="w-5 h-5 text-teal-600" />,
      title: "Local Google Maps Ranking",
      description: "We evaluate your Google Business Profile completeness and keyword visibility across your city.",
    },
    {
      icon: <Smartphone className="w-5 h-5 text-indigo-600" />,
      title: "Mobile UX & Conversion Friction",
      description: "We inspect your contact forms, phone click-throughs, and booking pathways.",
    },
    {
      icon: <MessageSquare className="w-5 h-5 text-emerald-600" />,
      title: "WhatsApp & Response Time",
      description: "We measure how fast an interested prospect receives preliminary answers.",
    },
  ];

  return (
    <>
      <section className="py-16 sm:py-20 bg-slate-900 text-white border-b border-slate-800">
        <Container size="xl">
          <div className="max-w-3xl space-y-4">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-semibold bg-slate-800 text-teal-400 border border-slate-700">
              <Sparkles className="w-3.5 h-3.5" />
              <span>100% Free · No Obligation</span>
            </div>
            <h1 className="text-3xl sm:text-5xl font-extrabold tracking-tight text-white leading-tight">
              Free Digital Presence & Lead Flow Audit
            </h1>
            <p className="text-base sm:text-lg text-slate-300 leading-relaxed font-normal">
              Find out exactly where your business is losing high-intent customers online. We inspect your local search ranking, website speed, and conversion pathways.
            </p>
          </div>
        </Container>
      </section>

      <section className="py-16 sm:py-24 bg-slate-50">
        <Container size="xl">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start">
            {/* Left: What We Inspect */}
            <div className="lg:col-span-5 space-y-6">
              <div className="bg-white p-6 sm:p-7 rounded-2xl border border-slate-200 shadow-card space-y-4">
                <div className="text-xs font-bold uppercase tracking-wider text-slate-400">
                  What We Inspect in Your Audit
                </div>
                <h3 className="text-lg font-bold text-slate-900">
                  Comprehensive 4-Pillar Scan
                </h3>

                <div className="space-y-4 pt-2">
                  {auditFeatures.map((item, idx) => (
                    <div key={idx} className="flex items-start gap-3.5 text-xs">
                      <div className="w-9 h-9 rounded-xl bg-slate-50 border border-slate-100 flex items-center justify-center shrink-0">
                        {item.icon}
                      </div>
                      <div>
                        <h4 className="font-bold text-slate-900">{item.title}</h4>
                        <p className="text-slate-600 mt-0.5 leading-relaxed">{item.description}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Turnaround & Guarantee */}
              <div className="bg-slate-900 text-white p-6 rounded-2xl border border-slate-800 shadow-darkCard space-y-3 text-xs">
                <div className="text-xs font-bold uppercase tracking-wider text-teal-400 flex items-center gap-1.5">
                  <Clock className="w-4 h-4 text-teal-400" />
                  <span>24-Hour Review Turnaround</span>
                </div>
                <p className="text-slate-300 leading-relaxed">
                  Your audit is generated by real product engineers, not automated junk templates. We review your city competition and deliver an actionable PDF / WhatsApp voice teardown.
                </p>
                <div className="pt-2 border-t border-slate-800 flex items-center gap-2 text-slate-400">
                  <ShieldCheck className="w-4 h-4 text-teal-400" />
                  <span>Zero hard sales pitches. Strictly actionable feedback.</span>
                </div>
              </div>
            </div>

            {/* Right: The Audit Form */}
            <div className="lg:col-span-7">
              <AuditForm defaultPackage={selectedPackage} />
            </div>
          </div>
        </Container>
      </section>
    </>
  );
}
